version: "3.9"

services:
  mongodb:
    image: mongo:7.0
    container_name: rental_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - rental_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rental_backend    
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    networks:
      - rental_network
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rental_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

    networks:
      - rental_network

networks:
  rental_network:
    driver: bridge

volumes:
  mongodb_data:
  frontend_node_modules:
