version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: rental_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    # 简化版本，无认证（仅开发环境）

volumes:
  mongodb_data: