[project]
name = "rental-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "autogen-agentchat>=0.5.7",
    "autogen-ext>=0.5.7",
    "openai>=1.82.0",
    "pyautogen>=0.9",
]
