/**
 * Market Analysis Overlay Component - Sci-fi Style
 * 
 * Features:
 * - Fetch market analysis data from backend API
 * - Display key market indicators in sci-fi style
 * - Support show/hide animation effects
 * - Responsive design for different screens
 */
class MarketAnalysisOverlay {
    constructor(config = {}) {
        this.config = {
            backendUrl: 'http://localhost:8000',
            overlayId: 'market-analysis-overlay',
            contentId: 'market-analysis-content',
            autoHideDelay: 30000, // Auto hide after 30 seconds
            ...config
        };
        
        this.isVisible = false;
        this.autoHideTimer = null;
        this.logger = null; // Logger, injected externally
    }

    /**
     * Initialize component
     */
    initialize(logger = null) {
        this.logger = logger;
        this.createOverlayHTML();
        this.bindEvents();
        this.log('info', '📊 Market analysis overlay initialized');
    }

    /**
     * Create overlay window HTML structure
     */
    createOverlayHTML() {
        // Check if already exists
        if (document.getElementById(this.config.overlayId)) {
            return;
        }

        const overlayHTML = `
            <div id="${this.config.overlayId}" class="market-analysis-overlay hidden">
                <div class="market-analysis-header">
                    <div class="market-analysis-title">📊 Market Analysis</div>
                    <button class="market-analysis-close" id="market-analysis-close">×</button>
                </div>
                <div class="market-analysis-content" id="${this.config.contentId}">
                    <!-- Content will be dynamically generated by JavaScript -->
                </div>
            </div>
        `;

        // Add HTML to body
        document.body.insertAdjacentHTML('beforeend', overlayHTML);
    }

    /**
     * Bind event handlers
     */
    bindEvents() {
        const closeBtn = document.getElementById('market-analysis-close');
        if (closeBtn) {
            closeBtn.addEventListener('click', () => this.hide());
        }

        // Close with ESC key
        document.addEventListener('keydown', (e) => {
            if (e.key === 'Escape' && this.isVisible) {
                this.hide();
            }
        });
    }

    /**
     * Fetch and display market analysis data from API
     */
    async fetchAndDisplay() {
        try {
            this.log('info', '📊 Fetching market analysis data...');

            const response = await fetch(`${this.config.backendUrl}/analysis/market/basic`, {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json',
                }
            });

            if (!response.ok) {
                throw new Error(`API request failed: ${response.status} ${response.statusText}`);
            }

            const analysisResult = await response.json();

            this.log('success', '✅ Market analysis data retrieved');
            console.log('📊 Market Analysis Result:', analysisResult);

            // Display analysis results
            this.displayAnalysis(analysisResult);

        } catch (error) {
            console.error('❌ Failed to fetch market analysis:', error);
            this.log('error', `Failed to get market analysis: ${error.message}`);
            
            // Display error message
            this.displayError(error.message);
        }
    }

    /**
     * Display market analysis window
     */
    displayAnalysis(analysisResult) {
        const overlay = document.getElementById(this.config.overlayId);
        const content = document.getElementById(this.config.contentId);
        
        if (!overlay || !content) {
            console.error('Market analysis overlay elements not found');
            return;
        }

        // Generate analysis content HTML
        const analysisHTML = this.generateAnalysisHTML(analysisResult);
        content.innerHTML = analysisHTML;

        // Show window
        this.show();
        
        this.log('info', '📊 Market analysis window displayed');
    }

    /**
     * Display error message
     */
    displayError(errorMessage) {
        const overlay = document.getElementById(this.config.overlayId);
        const content = document.getElementById(this.config.contentId);
        
        if (!overlay || !content) {
            return;
        }

        content.innerHTML = `
            <div class="market-metric-group">
                <div class="metric-group-title">❌ Error</div>
                <div class="metric-item">
                    <span class="metric-label" style="color: #ef4444;">${errorMessage}</span>
                </div>
                <div class="metric-item">
                    <span class="metric-label">Please try again later</span>
                </div>
            </div>
        `;

        this.show();
    }

    /**
     * Generate analysis HTML content
     */
    generateAnalysisHTML(data) {
        const { 
            tenant_metrics, 
            property_metrics, 
            supply_demand, 
            price_metrics, 
            market_health_indicator,
            api_metadata 
        } = data;

        if (!tenant_metrics || !property_metrics) {
            return '<div class="market-metric-group"><div class="metric-group-title">❌ Invalid Data</div></div>';
        }

        return `
            <!-- Tenant metrics -->
            <div class="market-metric-group">
                <div class="metric-group-title">🏠 Rental Market</div>
                <div class="metric-item">
                    <span class="metric-label">Total Tenants:</span>
                    <span class="metric-value">${tenant_metrics.total_tenants || 0}</span>
                </div>
                <div class="metric-item">
                    <span class="metric-label">Rental Rate:</span>
                    <span class="metric-value ${(tenant_metrics.rental_rate_percentage || 0) < 50 ? 'warning' : ''}">${tenant_metrics.rental_rate_percentage || 0}%</span>
                </div>
                <div class="metric-item">
                    <span class="metric-label">Avg Budget:</span>
                    <span class="metric-value">£${tenant_metrics.average_budget || 0}</span>
                </div>
            </div>

            <!-- Property metrics -->
            <div class="market-metric-group">
                <div class="metric-group-title">🏢 Property Market</div>
                <div class="metric-item">
                    <span class="metric-label">Available:</span>
                    <span class="metric-value">${property_metrics.available_properties || 0}</span>
                </div>
                <div class="metric-item">
                    <span class="metric-label">Occupancy Rate:</span>
                    <span class="metric-value ${(property_metrics.occupancy_rate_percentage || 0) < 50 ? 'warning' : ''}">${property_metrics.occupancy_rate_percentage || 0}%</span>
                </div>
                <div class="metric-item">
                    <span class="metric-label">Avg Rent:</span>
                    <span class="metric-value">£${property_metrics.average_rent ? property_metrics.average_rent.toFixed(0) : 0}</span>
                </div>
            </div>

            ${supply_demand ? `
            <!-- Supply & Demand -->
            <div class="market-metric-group">
                <div class="metric-group-title">⚖️ Supply & Demand</div>
                <div class="metric-item">
                    <span class="metric-label">Market Type:</span>
                    <span class="metric-value ${supply_demand.market_condition === "Buyer's Market" ? 'warning' : ''}">${supply_demand.market_condition || 'Unknown'}</span>
                </div>
                <div class="metric-item">
                    <span class="metric-label">S/D Ratio:</span>
                    <span class="metric-value">${supply_demand.supply_demand_ratio ? supply_demand.supply_demand_ratio.toFixed(1) : 'N/A'}</span>
                </div>
                <div class="metric-item">
                    <span class="metric-label">Tension:</span>
                    <span class="metric-value ${supply_demand.market_tension === 'Low' ? 'warning' : ''}">${supply_demand.market_tension || 'Unknown'}</span>
                </div>
            </div>
            ` : ''}

            ${price_metrics && price_metrics.price_ranges ? `
            <!-- Price ranges -->
            <div class="market-metric-group">
                <div class="metric-group-title">💰 Price Ranges</div>
                <div class="metric-item">
                    <span class="metric-label">< £1,000:</span>
                    <span class="metric-value">${price_metrics.price_ranges.under_1000 || 0}</span>
                </div>
                <div class="metric-item">
                    <span class="metric-label">£1K - £2K:</span>
                    <span class="metric-value">${(price_metrics.price_ranges['1000_1500'] || 0) + (price_metrics.price_ranges['1500_2000'] || 0)}</span>
                </div>
                <div class="metric-item">
                    <span class="metric-label">> £3,000:</span>
                    <span class="metric-value">${price_metrics.price_ranges.over_3000 || 0}</span>
                </div>
            </div>
            ` : ''}

            ${market_health_indicator ? `
            <!-- Market health indicator -->
            <div class="market-health-indicator">
                <div class="health-score ${(market_health_indicator.health_score || 0) < 30 ? 'danger' : (market_health_indicator.health_score || 0) < 60 ? 'warning' : ''}">${market_health_indicator.health_score ? market_health_indicator.health_score.toFixed(1) : 'N/A'}</div>
                <div class="health-status">${market_health_indicator.health_status || 'Unknown'}</div>
            </div>
            ` : ''}

            <!-- Timestamp -->
            <div class="analysis-timestamp">
                Updated: ${api_metadata && api_metadata.response_time ? new Date(api_metadata.response_time).toLocaleTimeString() : new Date().toLocaleTimeString()}
            </div>
        `;
    }

    /**
     * Show window
     */
    show() {
        const overlay = document.getElementById(this.config.overlayId);
        if (overlay) {
            overlay.classList.remove('hidden');
            overlay.classList.add('show');
            this.isVisible = true;
            // No auto-hide, user manually closes
        }
    }

    /**
     * Hide window
     */
    hide() {
        const overlay = document.getElementById(this.config.overlayId);
        if (overlay) {
            overlay.classList.add('hidden');
            overlay.classList.remove('show');
            this.isVisible = false;

            // Clear auto-hide timer
            this.clearAutoHideTimer();
        }
    }

    /**
     * Set auto-hide timer
     */
    // setAutoHideTimer removed: auto-hide disabled

    /**
     * Clear auto-hide timer
     */
    clearAutoHideTimer() {
        // No-op: auto-hide disabled
    }

    /**
     * Toggle display state
     */
    toggle() {
        if (this.isVisible) {
            this.hide();
        } else {
            this.fetchAndDisplay();
        }
    }

    /**
     * Logging
     */
    log(type, message) {
        if (this.logger && typeof this.logger.addLog === 'function') {
            this.logger.addLog(type, message);
        } else {
            console.log(`[MarketAnalysis] ${type}: ${message}`);
        }
    }

    /**
     * Destroy component
     */
    destroy() {
        this.clearAutoHideTimer();
        const overlay = document.getElementById(this.config.overlayId);
        if (overlay) {
            overlay.remove();
        }
        this.isVisible = false;
    }
}

export default MarketAnalysisOverlay;